name: Code Quality
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: pip install --upgrade pip
    - run: pip install "black<23" pylint==v3.0.0a3 mypy==v0.902 types-setuptools pytest "aiozmq<1" "django<5" "fastapi<1" "flask<3" "flask-socketio<5.3.1" "pyzmq" "sanic" "tornado<7" "websockets<11"
    - run: black --diff --check $(git ls-files -- '*.py' ':!:docs/*')
    - run: pylint --disable=all --enable=unused-import $(git ls-files -- '*.py' ':!:docs/*')
    - run: mypy --strict $(git ls-files -- '*.py' ':!:docs/*')
